stages:
  - test
  - build image
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "director_v2"
  MYSQL_USER: "director_v2"
  MYSQL_PASSWORD: "director_v2"
  SBT_OPTS: "-sbt-launch-dir .sbt/launchers -sbt-dir .sbt -ivy .ivy2 -Dsbt.color=true -Dscala.color=true"
  SERVICE: director

default:
  cache:
    key: director
    when: always
    paths:
      - .ivy2/
      - .sbt/
  image: registry.gitlab.com/torizon-platform/ci-container-build:scala-jvm17-0.0.5
  services:
    - name: mariadb:10.4
      alias: db
      command:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
        - --max_connections=1000
    - name: docker:dind

include:
  - project: torizon-platform/ci-container-build
    file: gitlab-ci-templates/gitlab-sbt-docker-publish.yaml
    ref: master
  - project: 'torizon-platform/deploy-env'
    ref: master
    file: '/gitlab/deploy-core-service.yml'


test:
  stage: test
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    DB_URL: "jdbc:mariadb://db:3306/$MYSQL_DATABASE"
  before_script:
    - env | grep CI_COMMIT_REF_NAME
    - echo "GRANT ALL PRIVILEGES ON \`director%\`.* TO 'director_v2'@'%'; FLUSH PRIVILEGES; " > db_user.sql
    - until mysqladmin ping --protocol=TCP -h db -P 3306 -u root -proot; do echo waiting for mysql; sleep 1; done
    - mysql -v -h db -u root -proot < db_user.sql
  script:
    - sbt test

build docker image:
  stage: build image
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  extends: .sbt-docker-publish
  variables:
    SERVICE_NAME: director-v2
    ROOT_LOG_LEVEL: debug
