name: Test & Build
on: [push, pull_request]
env:
  SBT_OPTS: "-Dsbt.color=true -Dscala.color=true"
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    container: uptane/ci:jvm17-latest
    services:
      db:
        image: mariadb:10.4
        env:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "director_v2"
          MYSQL_USER: "director_v2"
          MYSQL_PASSWORD: "director_v2"

    env:
      DB_URL: "jdbc:mariadb://db:3306/director_v2"

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - run: ./deploy/ci-db-setup.sh db
      - run: sbt test
